#ifndef SL_COMPONENT_CATALOG_H
#define SL_COMPONENT_CATALOG_H

// APIs present in project
#define SL_CATALOG_MX25_FLASH_SHUTDOWN_PRESENT
#define SL_CATALOG_LED0_PRESENT
#define SL_CATALOG_IOSTREAM_UART_PRESENT
#define SL_CATALOG_IOSTREAM_USART_PRESENT

#endif // SL_COMPONENT_CATALOG_H
