/* Copyright (c) Microsoft Corporation.
   Licensed under the MIT License. */

#ifndef _AZURE_CONFIG_H
#define _AZURE_CONFIG_H

// ----------------------------------------------------------------------------
// Azure IoT Hub Connection Transport
//    Define to use the legacy MQTT connection, else Azure RTOS SDK for Azure IoT
// ----------------------------------------------------------------------------
//#define ENABLE_LEGACY_MQTT

// ----------------------------------------------------------------------------
// Azure IoT Dynamic Provisioning Service
//    Define this to use the DPS service, otherwise direct IoT Hub
// ----------------------------------------------------------------------------
// #define ENABLE_DPS

// ----------------------------------------------------------------------------
// Azure IoT DPS Self-Signed X509Certificate
//    Define this to connect to DPS or Iot Hub using a self-signed X509
///   certificate
// ----------------------------------------------------------------------------
// #define ENABLE_X509

// ----------------------------------------------------------------------------
// Azure IoT Device ID
//    Make sure this is the same as the Device ID on the corresponding IoT Hub
//    NOTE: To be used only when ENABLE_DPS is NOT defined
// ----------------------------------------------------------------------------
#define IOT_DEVICE_ID ""

// ----------------------------------------------------------------------------
// Azure IoT SAS Key
//    The SAS key generated by configuring an IoT Hub device or DPS individual
//    enrollment
//    NOTE: To be used only when ENABLE_X509 is not defined
// ----------------------------------------------------------------------------
#define IOT_PRIMARY_KEY ""

// ----------------------------------------------------------------------------
// Azure IoT Hub Hostname
//    The Hostname found on your IoT Hub Overview page
//    NOTE: To be used only when ENABLE_DPS is not defined
// ----------------------------------------------------------------------------
#define IOT_HUB_HOSTNAME ""

// ----------------------------------------------------------------------------
// Azure IoT DPS config
//    DPS connection information
//    IOT_DPS_ENDPOINT is always "global.azure-devices-provisioning.net"
//    IOT_DPS_ID_SCOPE can be found on your DPS Overview page
//    IOT_DPS_REGISTRATION ID is the title of your individual enrollment
//    containing your SAS key or X509 certificate
// ----------------------------------------------------------------------------
#define IOT_DPS_ENDPOINT        "global.azure-devices-provisioning.net"
#define IOT_DPS_ID_SCOPE        ""
#define IOT_DPS_REGISTRATION_ID ""

#endif // _AZURE_CONFIG_H
