# Environment configuration
info:
  name: Connect an NXP MIMXRT1060-EVK Evaluation Kit to Azure IoT
  version: 1.0.0
  summary: Use Azure RTOS to connect an NXP MIMXRT1060-EVK Evaluation Kit to Azure IoT

requires:
  tools/ninja-build/ninja: 1.10.2
  tools/kitware/cmake: 3.20.1
  tools/compuphase/termite: 3.4.0
  compilers/arm/gcc: 2020.10.0
